// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz-F7uxCzC3zZ6j1HnpY2eHVjp-mvFYWw',
    appId: '1:91749336280:web:9ec37145230e6529b603ad',
    messagingSenderId: '91749336280',
    projectId: 'neo-f8c12',
    authDomain: 'neo-f8c12.firebaseapp.com',
    storageBucket: 'neo-f8c12.appspot.com',
    measurementId: 'G-Q5FE7X0NE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzynImmNGQXjbqPuCNN_dk0jk8Kedwh9I',
    appId: '1:91749336280:android:cb5f84e2d8b1671bb603ad',
    messagingSenderId: '91749336280',
    projectId: 'neo-f8c12',
    storageBucket: 'neo-f8c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxlqd1M4TnQB52lxiaxsQiF3KeKFuX-lM',
    appId: '1:91749336280:ios:868452f1e55b6703b603ad',
    messagingSenderId: '91749336280',
    projectId: 'neo-f8c12',
    storageBucket: 'neo-f8c12.appspot.com',
    iosBundleId: 'com.example.neo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxlqd1M4TnQB52lxiaxsQiF3KeKFuX-lM',
    appId: '1:91749336280:ios:f9e5cb4a9173610eb603ad',
    messagingSenderId: '91749336280',
    projectId: 'neo-f8c12',
    storageBucket: 'neo-f8c12.appspot.com',
    iosBundleId: 'com.example.neo.RunnerTests',
  );
}
